-- REPORT 1 --
SELECT 
  h.HOUSEHOLD_ID as ACCOUNT_NUMBER,
  r.NAME as RELATIONSHIP,
  hp.HOUSEHOLD_PERSON_ID as PATIENT_ID,
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as NAME,
  e.ADDRESS1,
  e.ADDRESS2,
  e.CITY,
  e.STATE,
  e.ZIP,
  e.PHONE1,
  e.PHONE2,
  e.PHONE3
FROM HOUSEHOLD h
JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
JOIN RELATIONSHIP r ON hp.RELATIONSHIP_ID = r.RELATIONSHIP_ID
ORDER BY h.HOUSEHOLD_ID;

-- REPORT 2 --
SELECT
  h.HOUSEHOLD_ID as ACCOUNT_NUMBER,
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as NAME,
  h.INSURANCE_NAME
FROM HOUSEHOLD h
JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
WHERE hp.IS_PAYER = 'Y'
ORDER BY e.NAME1, e.NAME2, e.NAME3;

-- REPORT 3 --
SELECT 
  hp.HOUSEHOLD_PERSON_ID as PATIENT_ID,
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as NAME,
  hp.DOB,
  h.INSURANCE_NAME,
  h.POLICY_NUMBER,
  h.GROUP_NUMBER
FROM HOUSEHOLD h
JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
JOIN RELATIONSHIP r ON hp.RELATIONSHIP_ID = r.RELATIONSHIP_ID
ORDER BY h.HOUSEHOLD_ID;

-- REPORT 4 --
SELECT 
  h.HOUSEHOLD_ID as ACCOUNT_NUMBER,
  payer.NAME as HOUSEHOLD_NAME,
  hp.HOUSEHOLD_PERSON_ID as PATIENT_ID,
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as PATIENT_NAME,
  s.NAME as SERVICE,
  asp.COST,
  asp.TIME as SERVICE_DATE
FROM HOUSEHOLD h
JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
JOIN (
  SELECT
    h.HOUSEHOLD_ID,
    e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as NAME
  FROM HOUSEHOLD h
  JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
  JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
  WHERE hp.IS_PAYER = 'Y'
) payer ON h.HOUSEHOLD_ID = payer.HOUSEHOLD_ID
JOIN APPOINTMENT a ON hp.HOUSEHOLD_PERSON_ID = a.HOUSEHOLD_PERSON_ID
JOIN APPOINTMENT_SERVICE asp ON a.APPOINTMENT_ID = asp.APPOINTMENT_ID
JOIN SERVICE s ON asp.SERVICE_ID = s.SERVICE_ID
ORDER BY payer.NAME, e.NAME1, e.NAME2, e.NAME3, asp.TIME;

-- REPORT 5 -- 
SELECT 
  payer.NAME as HOUSEHOLD_NAME,
  SUM(asp.COST) as TOTAL
FROM HOUSEHOLD h
JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
JOIN APPOINTMENT a ON hp.HOUSEHOLD_PERSON_ID = a.HOUSEHOLD_PERSON_ID
JOIN APPOINTMENT_SERVICE asp ON a.APPOINTMENT_ID = asp.APPOINTMENT_ID
JOIN (
  SELECT 
    hp.HOUSEHOLD_ID, 
    SUM(aps.COST) as TOTAL
  FROM HOUSEHOLD_PERSON hp
  JOIN APPOINTMENT a ON hp.HOUSEHOLD_PERSON_ID = a.HOUSEHOLD_PERSON_ID
  JOIN APPOINTMENT_SERVICE aps ON a.APPOINTMENT_ID = aps.APPOINTMENT_ID
  GROUP BY hp.HOUSEHOLD_ID
) totals ON h.HOUSEHOLD_ID = totals.HOUSEHOLD_ID
JOIN (
  SELECT
    h.HOUSEHOLD_ID,
    e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as NAME
  FROM HOUSEHOLD h
  JOIN HOUSEHOLD_PERSON hp ON h.HOUSEHOLD_ID = hp.HOUSEHOLD_ID
  JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
  WHERE hp.IS_PAYER = 'Y'
) payer ON h.HOUSEHOLD_ID = payer.HOUSEHOLD_ID
GROUP BY payer.NAME
ORDER BY payer.NAME;

-- REPORT 6 --
SELECT
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as PROVIDER,
  s.NAME as QUALIFIED_SERVICE
FROM PROVIDER p
JOIN PROVIDER_QUALIFICATION pq ON p.PROVIDER_ID = pq.PROVIDER_ID
JOIN SERVICE s ON pq.SERVICE_ID = s.SERVICE_ID
JOIN ENTITY e ON p.ENTITY_ID = e.ENTITY_ID
ORDER BY e.NAME1, e.NAME2, e.NAME3, s.NAME;

-- REPORT 7 --
SELECT 
  s.NAME as SERVICE,
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as QUALIFIED_PROVIDER
FROM SERVICE s
JOIN PROVIDER_QUALIFICATION pq ON s.SERVICE_ID = pq.SERVICE_ID
JOIN PROVIDER p ON pq.PROVIDER_ID = p.PROVIDER_ID
JOIN ENTITY e ON p.ENTITY_ID = e.ENTITY_ID
ORDER BY s.NAME, e.NAME1, e.NAME2, e.NAME3;

-- REPORT 8 --
SELECT
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as PATIENT,
  asp.TIME as APPOINTMENT_DATE,
  s.MINUTES,
  e.PHONE1 as PHONE
FROM APPOINTMENT_SERVICE asp
JOIN APPOINTMENT a ON asp.APPOINTMENT_ID = a.APPOINTMENT_ID
JOIN HOUSEHOLD_PERSON hp ON a.HOUSEHOLD_PERSON_ID = hp.HOUSEHOLD_PERSON_ID
JOIN ENTITY e ON hp.ENTITY_ID = e.ENTITY_ID
JOIN SERVICE s ON asp.SERVICE_ID = s.SERVICE_ID
WHERE asp.TIME > SYSDATE
ORDER BY e.NAME1, e.NAME2, e.NAME3, asp.TIME;

-- REPORT 9 --
SELECT 
  e.NAME1 || ' ' || e.NAME2 || ' ' || e.NAME3 as PROVIDER,
FROM PROVIDER p
JOIN APPOINTMENT_SERVICE asp ON p.PROVIDER_ID = asp.PROVIDER_ID
JOIN SERVICE s ON asp.SERVICE_ID = s.SERVICE_ID
JOIN ENTITY e ON p.ENTITY_ID = e.ENTITY_ID